[build]
  command = "npm run build"
  publish = "dist"

# Fingerprinted bundles (safe to cache forever)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Your /images aren’t fingerprinted → cache, but not forever (30 days)
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# Icons & manifest change occasionally → 7 days
[[headers]]
  for = "/favicon*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/apple-touch-icon.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/android-chrome-*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# HTML should always revalidate
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# SPA routing (very important for /city/... etc.)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

